
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-app-vuln
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:AxelPlault/TP-devsecops.git
    targetRevision: main
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: node-app-vuln
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
