
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-vuln
  namespace: node-app-vuln
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app-vuln
  template:
    metadata:
      labels:
        app: node-app-vuln
    spec:
      containers:
        - name: node-app-vuln
          image: localhost:5000/node-app-vuln:latest    # <-- ton image Docker Hub
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
