
name: CI/CD - Trivy Scan Python Apps

on:
  push:
    branches:
      - ci-cd-trivy-test
      - main

jobs:
  app-sec:
    name: trivy-scan (app-sec)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build app-sec image
        run: docker build -t app-sec -f app-sec/Dockerfile app-sec

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin
      - name: Check Trivy
        run: trivy --version

      # Non bloquant (toujours vert pour app-sec)
      - name: Scan app-sec with Trivy (non-blocking)
        run: trivy image --exit-code 0 --severity HIGH,CRITICAL app-sec

  app-vuln:
    name: trivy-scan (app-vuln)
    runs-on: ubuntu-latest
    continue-on-error: true   # <-- Autorise l'Ã©chec sans casser le run global
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build app-vuln image
        run: docker build -t app-vuln -f app-vuln/Dockerfile app-vuln

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin
      - name: Check Trivy
        run: trivy --version

      # Bloquant pour montrer le rouge sur app-vuln
      - name: Scan app-vuln with Trivy (blocking)
        run: trivy image --exit-code 1 --severity HIGH,CRITICAL app-vuln
